

import React, { useState } from 'react';
import { motion, AnimatePresence, Variants } from 'framer-motion';
import { ChevronDown } from 'lucide-react';

const sectionVariants: Variants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
        opacity: 1,
        y: 0,
        transition: { duration: 0.8, ease: [0.6, -0.05, 0.01, 0.99] }
    }
};

const AccordionItem = ({ title, children }: { title: string, children: React.ReactNode }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div className="border-b border-gray-200 dark:border-gray-700 py-4">
            <button onClick={() => setIsOpen(!isOpen)} className="w-full flex justify-between items-center text-left">
                <span className="text-lg font-semibold">{title}</span>
                <motion.div animate={{ rotate: isOpen ? 180 : 0 }}>
                    <ChevronDown size={24} />
                </motion.div>
            </button>
            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="overflow-hidden"
                    >
                        <div className="pt-4 text-gray-600 dark:text-gray-400">{children}</div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}

const FAQ: React.FC = () => (
    <motion.section
        id="faq"
        className="py-16 md:py-24"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.2 }}
        variants={sectionVariants}
    >
        <div className="container mx-auto px-6 max-w-3xl">
            <h2 className="text-4xl font-bold text-center mb-12">Frequently Asked Questions</h2>
            {/* FIX: The error suggests children are missing. Ensured children are correctly passed to each AccordionItem component. */}
            <AccordionItem title="Who is DeepThink for?">
                <p>DeepThink is designed for professionals in any field who rely on critical decision-making skills. This includes leaders, managers, strategists, and specialists in tech, business, engineering, and more.</p>
            </AccordionItem>
            {/* FIX: The error suggests children are missing. Ensured children are correctly passed to each AccordionItem component. */}
            <AccordionItem title="How are scenarios generated?">
                <p>Our scenarios are generated by a sophisticated AI model, tailored to your specific job role and experience level. You can also create your own custom scenarios to target specific skills you want to develop.</p>
            </AccordionItem>
            {/* FIX: The error suggests children are missing. Ensured children are correctly passed to each AccordionItem component. */}
            <AccordionItem title="Is my performance data private?">
                <p>Yes, your individual performance data and analysis reports are completely private to your account. We only use anonymized, aggregated data to improve our AI models and overall platform.</p>
            </AccordionItem>
            {/* FIX: The error suggests children are missing. Ensured children are correctly passed to each AccordionItem component. */}
            <AccordionItem title="Can I use DeepThink with my team?">
                <p>Absolutely! We offer an Enterprise plan that includes team management features, custom scenario creation for your organization, and aggregate team analytics. Please contact our sales team for more information.</p>
            </AccordionItem>
            {/* FIX: The error suggests children are missing. Ensured children are correctly passed to each AccordionItem component. */}
            <AccordionItem title="What if I don't have a subscription?">
                <p>Our Starter plan is completely free and allows you to try one scenario per month. This is a great way to experience the core functionality of DeepThink before upgrading to a Pro plan for unlimited access.</p>
            </AccordionItem>
        </div>
    </motion.section>
);

export default FAQ;